package aa.bb.auto;

import org.apache.cayenne.Persistent;

/** 
 * Embeddable class _Embeddable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually, 
 * since it may be overwritten next time code is regenerated. 
 * If you need to make any customizations, please use subclass. 
 */
public abstract class _Embeddable extends Object {


    // special properties injected by Cayenne
    private Persistent owner;
    private String embeddedProperty;
    
    // declared properties

    // lifecycle methods
    protected void propertyWillChange(String property, Object oldValue, Object newValue) {
        if (owner != null && owner.getObjectContext() != null) {
            owner.getObjectContext().propertyChanged(
                    owner,
                    embeddedProperty + "." + property,
                    oldValue,
                    newValue);
        }
    }

    // declared getters and setters
}
